[package]
name    = "rapier-examples-3d"
version = "0.1.0"
authors = [ "SÃ©bastien Crozet <developer@crozet.re>" ]
edition = "2018"
default-run = "all_examples3"

[features]
parallel = [ "rapier3d/parallel", "rapier_testbed3d/parallel" ]
simd-stable = [ "rapier3d/simd-stable" ]
simd-nightly = [ "rapier3d/simd-nightly" ]
other-backends = [ "rapier_testbed3d/other-backends" ]
enhanced-determinism = [ "rapier3d/enhanced-determinism" ]

[dependencies]
rand = "0.8"
getrandom = { version = "0.2", features = [ "js" ] } 
Inflector  = "0.11"
nalgebra   = "0.26"
kiss3d     = "0.31"

[dependencies.rapier_testbed3d]
path = "../build/rapier_testbed3d"

[dependencies.rapier3d]
path = "../build/rapier3d"

[[bin]]
name = "all_examples3"
path = "./all_examples3.rs"

[[bin]]
name = "harness_capsules3"
path = "./harness_capsules3.rs"
